=== qinweiwei/sahara/sahara-2014.1.1/sahara/plugins/intel/v2_5_1/resources/configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:complexType name="display">
    <xs:sequence>
      <xs:element name="en">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="1" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="valueType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Boolean" />
      <xs:enumeration value="Integer" />
      <xs:enumeration value="Float" />
      <xs:enumeration value="IP" />
      <xs:enumeration value="Port" />
      <xs:enumeration value="IPWithPort" />
      <xs:enumeration value="IPWithMask" />
      <xs:enumeration value="URL" />
      <xs:enumeration value="String" />
      <xs:enumeration value="MepRedCapacity" />
      <xs:enumeration value="HBaseClientScannerCaching" />
      <xs:enumeration value="Class" />
      <xs:enumeration value="Choose" />
      <xs:enumeration value="Directory" />
      <xs:enumeration value="Int_range" />
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="configuration">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element name="property" maxOccurs="unbounded">
          <xs:complexType>
            <xs:all>
              <xs:element name="name" type="xs:string" />
              <xs:element name="value" type="xs:string" />
              <xs:element name="intel_default" type="xs:string" minOccurs="0" />
              <xs:element name="recommendation" type="xs:string" minOccurs="0" />
              <xs:element name="valuetype" type="valueType" />
              <xs:element name="group" type="xs:string" />
              <xs:element name="definition" type="display" />
              <xs:element name="description" type="display" />
              <xs:element name="global" type="xs:boolean" minOccurs="0" />
              <xs:element name="allowempty" type="xs:boolean" minOccurs="0" />
              <xs:element name="readonly" type="xs:boolean" minOccurs="0" />
              <xs:element name="hide" type="xs:boolean" minOccurs="0" />
              <xs:element name="automatic" type="xs:boolean" minOccurs="0" />
              <xs:element name="enable" type="xs:boolean" minOccurs="0" />
              <xs:element name="reserved" type="xs:boolean" minOccurs="0" />
              <xs:element name="radios" type="xs:string" minOccurs="0" />
              <xs:element name="script" type="xs:string" minOccurs="0" />
              <xs:element name="type" type="xs:string" minOccurs="0" />
              <xs:element name="form" type="xs:string" minOccurs="0" />
              <xs:element name="chooselist" type="xs:string" minOccurs="0" />
              <xs:element name="implementation" type="xs:string" minOccurs="0" />
              <xs:element name="sectionname" type="xs:string" minOccurs="0" />
              <xs:element name="refor" minOccurs="0">
                <xs:complexType>
                  <xs:all>
                    <xs:element name="refand">
                      <xs:complexType>
                        <xs:all>
                          <xs:element name="value" type="xs:string" />
                          <xs:element name="valuetype" type="valueType" />
                          <xs:element name="index" type="xs:string" />
                        </xs:all>
                      </xs:complexType>
                    </xs:element>
                  </xs:all>
                </xs:complexType>
              </xs:element>
            </xs:all>
            <xs:attribute name="skipInDoc" type="xs:boolean" />
          </xs:complexType>
        </xs:element>
        <xs:element name="briefsection" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:all>
              <xs:element name="sectionname" type="xs:string" />
              <xs:element name="name_en" type="xs:string" />
              <xs:element name="description_en" type="xs:string" minOccurs="0" />
              <xs:element name="autoexpand" type="xs:boolean" />
              <xs:element name="showdescription" type="xs:boolean" />
            </xs:all>
          </xs:complexType>
        </xs:element>
        <xs:element name="group" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:all>
              <xs:element name="id" type="xs:string" />
              <xs:element name="name_en" type="xs:string" />
              <xs:element name="description_en" type="xs:string" />
            </xs:all>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== qinweiwei/sahara/sahara-2014.1.1/sahara/plugins/intel/v2_5_1/resources/mapred-default.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
<!-- Do not modify this file directly. Instead, copy entries that you -->
<!-- wish to modify from this file into mapred-site.xml and change them -->
<!-- there. If mapred-site.xml does not already exist, create it. -->
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="configuration.xsd">
    <property>
        <name>hadoop.jobtracker.memory</name>
        <value>4096</value>
        <valuetype>Integer</valuetype>
        <group>jobtracker</group>
        <definition>
            <en>JobTracker server memory size</en>
        </definition>
        <type>1</type>
        <automatic>true</automatic>
        <reserved>true</reserved>
        <description>
            <en>Default size for jobtracker server memory.</en>
        </description>
    </property>
    <property>
        <name>hadoop.tasktracker.slot.memory</name>
        <value>4096</value>
        <valuetype>Integer</valuetype>
        <group>tasktracker</group>
        <definition>
            <en>Total memory size for tasktracker map and reduce slot</en>
        </definition>
        <type>1</type>
        <automatic>true</automatic>
        <reserved>true</reserved>
        <description>
            <en>Total memory size for tasktracker map and reduce slot.</en>
        </description>
    </property>
    <property>
        <name>hadoop.tasktracker.memory</name>
        <value>4096</value>
        <valuetype>Integer</valuetype>
        <group>tasktracker</group>
        <definition>
            <en>Default size for tasktracker server memory</en>
        </definition>
        <type>1</type>
        <automatic>true</automatic>
        <reserved>true</reserved>
        <description>
            <en>Default size for tasktracker server memory.</en>
        </description>
    </property>
    <property>
        <name>hadoop.job.history.location</name>
        <value></value>
        <allowempty>true</allowempty>
        <valuetype>String</valuetype>
        <group>basic</group>
        <definition>
            <en>job history location</en>
        </definition>
        <description>
            <en> If job tracker is static the history files are stored
  in this single well known place. If No value is set here, by default,
  it is in the local file system at ${hadoop.log.dir}/history.
  </en>
        </description>
    </property>
    <property>
        <name>hadoop.job.history.user.location</name>
        <value></value>
        <allowempty>true</allowempty>
        <valuetype>String</valuetype>
        <group>basic</group>
        <definition>
            <en>user specified history location</en>
        </definition>
        <description>
            <en> User can specify a location to store the history files of
  a particular job. If nothing is specified, the logs are stored in
  output directory. The files are stored in "_logs/history/" in the directory.
  User can stop logging by giving the value "none".
  </en>
        </description>
    </property>
    <property>
        <name>mapred.job.tracker.history.completed.location</name>
        <value></value>
        <allowempty>true</allowempty>
        <valuetype>String</valuetype>
        <group>basic</group>
        <definition>
            <en>The completed job history files location</en>
        </definition>
        <description>
            <en> The completed job history files are stored at this single well
  known location. If nothing is specified, the files are stored at
  ${hadoop.job.history.location}/done.
  </en>
        </description>
    </property>
    <!-- i/o properties -->
    <property>
        <name>io.sort.factor</name>
        <value>10</value>
        <intel_default>10</intel_default>
        <recommendation>100</recommendation>
        <valuetype>Integer</valuetype>
        <group>perf</group>
        <definition>
            <en>IO sort factor</en>
        </definition>
        <description>
            <en>The number of streams to merge at once while sorting
  files.  This determines the number of open file handles.</en>
        </description>
    </property>
    <property>
        <name>io.sort.mb</name>
        <value>100</value>
        <intel_default>100</intel_default>
                <recommendation>200</recommendation>
        <valuetype>Integer</valuetype>
        <group>perf</group>
        <definition>
            <en>Total amount of buffer memory to use while sorting
  files,</en>
        </definition>
        <description>
            <en>The total amount of buffer memory to use while sorting
  files, in megabytes.  By default, gives each merge stream 1MB, which
  should minimize seeks.</en>
        </description>
    </property>
    <property>
        <name>io.sort.record.percent</name>
        <value>0.05</value>
        <valuetype>Float</valuetype>
        <group>perf</group>
        <definition>
            <en>The percentage of io.sort.mb dedicated to tracking record
  boundaries</en>
        </definition>
        <description>
            <en>The percentage of io.sort.mb dedicated to tracking record
  boundaries. Let this value be r, io.sort.mb be x. The maximum number
  of records collected before the collection thread must block is equal
  to (r * x) / 4</en>
        </description>
    </property>
    <property>
        <name>io.sort.spill.percent</name>
        <value>0.80</value>
        <valuetype>Float</valuetype>
        <group>perf</group>
        <definition>
            <en>buffer limit</en>
        </definition>
        <description>
            <!-- not sure what it means -->
            <en>The soft limit in either the buffer or record collection
  buffers. Once reached, a thread will begin to spill the contents to disk
  in the background. Note that this does not imply any chunking of data to
  the spill. A value less than 0.5 is not recommended.</en>
        </description>
    </property>
    <property>
        <name>io.map.index.skip</name>
        <value>0</value>
        <valuetype>Integer</valuetype>
        <group>io</group>
        <definition>
            <en>Number of index entries to skip between each entry</en>
        </definition>
        <description>
            <en>Number of index entries to skip between each entry.
  Zero by default. Setting this to values larger than zero can
  facilitate opening large map files using less memory.</en>
        </description>
    </property>
    <property>
        <name>mapred.job.tracker</name>
        <enable>false</enable>
        <value>local</value>
        <recommendation></recommendation>
        <allowempty>true</allowempty>
        <valuetype>String</valuetype>
        <group>jobtracker</group>
        <definition>
            <en>The host and port that the MapReduce job tracker runs
  at</en>
        </definition>
        <description>
            <en>The host that the MapReduce job tracker runs
  at.  If "local", then jobs are run in-process as a single map
  and reduce task.
  </en>
        </description>
    </property>
  <property>
    <name>mapred.jobtracker</name>
    <readonly>true</readonly>
    <value></value>
    <allowempty>true</allowempty>
    <valuetype>String</valuetype>
    <global>true</global>
    <group>jobtracker</group>
    <definition>
      <en>The address that the job tracker runs at</en>
    </definition>
    <sectionname>directory</sectionname>
    <description>
      <en>The host and port that the MapReduce job tracker runs
  at.  If "local", then jobs are run in-process as a single map
  and reduce task.
  </en>
    </description>
    <form>TextItem</form>
  </property>
    <property>
        <name>mapred.jobtracker.port</name>
        <value>54311</value>
        <valuetype>Integer</valuetype>
        <group>jobtracker</group>
        <definition>
            <en>The port that the MapReduce job tracker runs
  at</en>
        </definition>
        <global>true</global>
        <description>
            <en>The port that the MapReduce job tracker runs
  at.  If "local", then jobs are run in-process as a single map
  and reduce task.
  </en>
        </description>
    </property>
    <property>
        <name>hadoop.jobtracker.thrift.port</name>
        <value>9290</value>
        <valuetype>Integer</valuetype>
        <group>jobtracker</group>
        <definition>
            <en>The port for jobtracker thrift server.</en>
        </definition>
        <global>true</global>
        <description>
            <en>The port for jobtracker thrift server.</en>
        </description>
    </property>
    <property>
        <name>mapred.job.tracker.http.address</name>
        <value>0.0.0.0:50030</value>
        <valuetype>String</valuetype>
        <group>jobtracker</group>
        <definition>
            <en>The job tracker http server address and port</en>
        </definition>
        <description>
            <en>
    The job tracker http server address and port the server will listen on.
    If the port is 0 then the server will start on a free port.
  </en>
        </description>
    </property>
    <property>
        <name>mapred.job.tracker.handler.count</name>
        <value>10</value>
        <intel_default>10</intel_default>
                 <recommendation>60</recommendation>
        <valuetype>Integer</valuetype>
        <group>jobtracker</group>
        <definition>
            <en>The number of server threads for the JobTracker.</en>
        </definition>
        <description>
            <en>
    The number of server threads for the JobTracker. This should be roughly
    4% of the number of tasktracker nodes.
  </en>
        </description>
    </property>
    <property>
        <name>mapred.task.tracker.report.address</name>
        <value>127.0.0.1:0</value>
        <valuetype>String</valuetype>
        <group>tasktracker</group>
        <definition>
